### ISSUE TITLE
The Website of the TinyVIRAT shows PageNotFound.

### ISSUE THREAD

**Issue by xqcn** [UgurDemir/Tiny-VIRAT#1]
Please check the link of the dataset: [https://www.crcv.ucf.edu/datasets/ugur/TinyVIRAT.zip](https://www.crcv.ucf.edu/datasets/ugur/TinyVIRAT.zip)

**Comment by vyzuer** [comment]
@xqcn It should be there, let me know if there is any issue downloading. Also check out this CVPR-2021 challenge,
https://www.crcv.ucf.edu/tiny-actions-challenge-cvpr2021/. 
You might be interested in this.
